os: linux
dist: focal
language: generic
addons:
    apt:
        packages:
            - clang-format-11
before_install:
    - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.15.0/bazelisk-linux-amd64
    - chmod +x bazelisk-linux-amd64
    - sudo ln -s $(realpath bazelisk-linux-amd64) /usr/local/bin/bazelisk
    - sudo ln -s $(realpath bazelisk-linux-amd64) /usr/local/bin/bazel
script:
    - ./clang-format.sh
    - bazel build --config windows ...
    - bazel build --config linux ...
    - bazel test --config linux ...
