os: linux
dist: focal
language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        packages:
            - cmake
            - cmake-data
            - xorg-dev
script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
    - ctest -V
