package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "client_tiles",
    srcs = [
        "client_tiles.c",
        "schema.c",
        "schema.h",
        "seeder.c",
        "seeder.h",
    ],
    includes = ["."],
    deps = [
        "//client",
    ],
)
