#include "shoveler/material/depth.h"
#include "shoveler/shader_cache.h"
#include "shoveler/shader_program.h"

static const char *vertexShaderSource =
		"#version 400\n"
		""
		"uniform mat4 model;\n"
		"uniform mat4 modelNormal;\n"
		"uniform mat4 view;\n"
		"uniform mat4 projection;\n"
		"uniform mat4 lightView;\n"
		"uniform mat4 lightProjection;\n"
		""
		"in vec3 position;\n"
		"in vec3 normal;\n"
		"in vec2 uv;\n"
		""
		"out vec3 worldPosition;"
		"out vec3 worldNormal;"
		"out vec2 worldUv;"
		"out vec4 lightFrustumPosition4;"
		""
		"void main()\n"
		"{\n"
		"	vec4 worldPosition4 = model * vec4(position, 1.0);\n"
		"	vec4 worldNormal4 = modelNormal * vec4(normal, 1.0);\n"
		"	worldPosition = worldPosition4.xyz / worldPosition4.w;\n"
		"	worldNormal = worldNormal4.xyz / worldNormal4.w;\n"
		"	worldUv = uv;\n"
		""
		"	lightFrustumPosition4 = lightProjection * lightView * worldPosition4;\n"
		""
		"	gl_Position = projection * view * worldPosition4;\n"
		"}\n";

static const char *fragmentShaderSource =
		"#version 400\n"
		""
		"uniform vec3 cameraPosition;\n"
		""
		"uniform vec3 lightColor;\n"
		"uniform float lightAmbientFactor;\n"
		"uniform float lightExponentialShadowFactor;\n"
		"uniform vec3 lightPosition;\n"
		"uniform bool isExponentialLiftedShadowMap;\n"
		"uniform sampler2D shadowMap;\n"
		""
		"uniform vec3 color;\n"
		""
		"in vec3 worldPosition;\n"
		"in vec3 worldNormal;\n"
		"in vec2 worldUv;\n"
		"in vec4 lightFrustumPosition4;\n"
		""
		"out vec4 fragmentColor;\n"
		""
		"bool isInLightCamera(vec3 lightScreenPosition)\n"
		"{\n"
		"	return lightScreenPosition.x >= 0.0 && lightScreenPosition.x <= 1.0 && lightScreenPosition.y >= 0.0 && lightScreenPosition.y <= 1.0;\n"
		"}\n"
		""
		"float getExponentialShadowFactor(float shadowMapDepth, float fragmentDepth)\n"
		"{\n"
		"	if(isExponentialLiftedShadowMap) {\n"
		"		return clamp(shadowMapDepth * exp(-fragmentDepth * lightExponentialShadowFactor), 0.0, 1.0);\n"
		"	} else {\n"
		"		return clamp(exp(shadowMapDepth * lightExponentialShadowFactor) * exp(-fragmentDepth * lightExponentialShadowFactor), 0.0, 1.0);\n"
		"	}\n"
		"}\n"
		""
		"void main()\n"
		"{\n"
		"	vec3 lightFrustumPosition = lightFrustumPosition4.xyz / lightFrustumPosition4.w;\n"
		"	vec3 lightScreenPosition = 0.5 * (lightFrustumPosition + vec3(1.0, 1.0, 1.0));\n"
		"	float exponentialShadowFactor = 0.0;\n"
		"	if(isInLightCamera(lightScreenPosition)) {\n"
		"		float shadowMapDepth = texture2D(shadowMap, lightScreenPosition.xy).r;\n"
		"		float fragmentDepth = lightScreenPosition.z;\n"
		"		exponentialShadowFactor = getExponentialShadowFactor(shadowMapDepth, fragmentDepth);\n"
		"	}\n"
		""
		"	vec3 lightDirection = normalize(worldPosition - lightPosition);\n"
		"	vec3 normal = normalize(worldNormal);\n"
		""
		"	float diffuseFactor = clamp(dot(-lightDirection, normal), 0.0, 1.0);\n"
		""
		"	vec3 cameraDirection = normalize(cameraPosition - worldPosition);\n"
		"	vec3 reflectedLight = -reflect(-lightDirection, normal);\n"
		"	float specularFactor = pow(clamp(dot(reflectedLight, cameraDirection), 0.0, 1.0), 250.0);\n"
		""
		"	fragmentColor = vec4(clamp(lightAmbientFactor * color + exponentialShadowFactor * diffuseFactor * color * lightColor + exponentialShadowFactor * specularFactor * lightColor, 0.0, 1.0), 1.0);\n"
		"}\n";

ShovelerMaterial *shovelerMaterialColorCreate(ShovelerShaderCache *shaderCache, ShovelerVector3 color)
{
	GLuint vertexShaderObject = shovelerShaderProgramCompileFromString(vertexShaderSource, GL_VERTEX_SHADER);
	GLuint fragmentShaderObject = shovelerShaderProgramCompileFromString(fragmentShaderSource, GL_FRAGMENT_SHADER);
	GLuint program = shovelerShaderProgramLink(vertexShaderObject, 0, fragmentShaderObject, true);

	ShovelerMaterial *material = shovelerMaterialCreate(shaderCache, program);

	shovelerUniformMapInsert(material->uniforms, "color", shovelerUniformCreateVector3(color));

	return material;
}
