package(default_visibility = ["//visibility:public"])

cc_library(
    name = "server",
    srcs = [
        "server.c",
        "server.h",
    ],
    includes = ["."],
    deps = [
        "//schema",
    ],
)
