package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "local",
    srcs = [
        "local.c",
    ],
    includes = ["."],
    deps = [
        "//tiles/client",
        "//tiles/server",
    ],
)
