package(default_visibility = ["//visibility:public"])

cc_library(
    name = "client",
    srcs = [
        "client.c",
        "client.h",
    ],
    includes = ["."],
    deps = [
        "//client",
    ],
)
